name: Automation trigger to launch containers
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy scripts and necessary files via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "secrets.gpg"
        target: "trigger"
        
    - name: executing scripts
      uses: appleboy/ssh-action@master
      env:
        EXKEY: ${{ secrets.EXKEY }}
        IP: ${{ secrests.HOST }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }} 
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs : EXKEY
        script: |
          curl -s https://raw.githubusercontent.com/devsecopscloset/components/master/dev/setup.sh -o ~/trigger/setup.sh
          chmod +x $HOME/trigger/setup.sh
          export EXKEY=${{ secrets.EXKEY }}
          /bin/bash $HOME/trigger/setup.sh
          curl -s https://raw.githubusercontent.com/devsecopscloset/components/master/dev/trigger.sh -o ~/trigger/trigger.sh
          chmod +x $HOME/trigger/trigger.sh
          /bin/bash $HOME/trigger/trigger.sh
          export IP=${{ secrests.HOST }}
          echo $IP > $HOME/config/ip_vol/dd_ip.yaml
          echo ${{ secrets.HOST }} > $HOME/config/ip_vol/dd_ip.yaml
          rm -rf ~/trigger