name: Automation trigger to launch containers
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy scripts and necessary files via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "secrets.gpg"
        target: "trigger"
        
    - name: executing scripts
      uses: appleboy/ssh-action@master
      env:
        EXKEY: ${{ secrets.EXKEY }}
        IP: ${{ secrets.HOST }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }} 
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs : EXKEY
        script: |
          echo ${{ secrets.EXKEY }} > $HOME/hello.txt
